defaultContentLanguage = "zh-cn" # 默认语言
defaultContentLanguageInSubdir = true
baseURL = 'xenojf.com' # 你购买的域名
languageCode = 'zh-cn'
title = "john's Blog" # Blog title 
theme = ["github.com/onweru/newsroom"] # 你选择的主题
hasCJKLanguage = true # CJK 为中国, 日本, 韩国的缩写
canonifyurls = true
paginate = 6


[module]
[[module.imports]]
    path = 'github.com/onweru/newsroom' # 使用 hugo mod 管理主题